[workspace]
authors = ["ApaBila <salsabila.mahdi@gmail.com>"]
channels = ["conda-forge"]
name = "agentarium"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10"
agentarium = ">=0.2.8,<0.3"
